version: '2.1'

services:
  shippied:
    build: scs-101-shippied
    mem_limit: 512m
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8084:8084"
  shipping:
    build: scs-101-shipping
    mem_limit: 512m
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8083:8083"
  