spring.application.name: scs-101-inventory-check
spring.cloud.stream.bindings:
  inventoryCheck-in-0.destination: scs-101.inventoryCheck
  inventoryCheck-out-0.destination: scs-101.orderStatus
server.port: 8082
logging.level.com.ehsaniara.scs_kafka_intro: debug
elastic.apm.enabled: false
---
spring:
  config.activate.on-profile: kube
  cloud.stream.kafka.streams.binder.brokers: my-cluster-kafka-bootstrap.kafka:9092
elastic.apm.enabled: false