spring:
  application.name: scs-100-2
  cloud.function.definition: orderStateStoreProcessor;orderProcess;inventoryCheck;shipping;shippedConsumer

spring.cloud.stream:
  bindings:
    orderStateStoreProcessor-in-0.destination: scs-100-2.orderStatus
    orderStateStoreProcessor-out-0.destination: scs-100-2.orderProcess

    orderProcess-in-0.destination: scs-100-2.orderProcess
    orderProcess-out-0.destination: scs-100-2.inventoryCheck
    orderProcess-out-1.destination: scs-100-2.shipping
    orderProcess-out-2.destination: scs-100-2.shipped

    inventoryCheck-in-0.destination: scs-100-2.inventoryCheck
    inventoryCheck-out-0.destination: scs-100-2.orderStatus

    shipping-in-0.destination: scs-100-2.shipping
    shipping-out-0.destination: scs-100-2.orderStatus

    shippedConsumer-in-0.destination: scs-100-2.shipped

  kafka.streams:
    bindings:
      orderStateStoreProcessor-in-0.consumer.configuration.application.id: ${spring.application.name}-orderStateStoreProcessor
      orderProcess-in-0.consumer.configuration.application.id: ${spring.application.name}-orderProcess
      inventoryCheck-in-0.consumer.configuration.application.id: ${spring.application.name}-inventoryCheck
      shipping-in-0.consumer.configuration.application.id: ${spring.application.name}-shipping
      shippedConsumer-in-0.consumer.configuration.application.id: ${spring.application.name}-shipped
    binder:
      brokers: localhost:9092 # just to use it in the service app, Its already 'localhost:9092' by default
      auto-add-partitions: true
      min-partition-count: 6
      state-store-retry:
        max-attempts: 10
        backoff-period: 500
      configuration:
        application.id: ${spring.application.name}
        application.server: localhost:${server.port:8080} # for InteractiveQueryService to describe itself
        state.dir: state-${spring.application.name}-${server.port} # to give a unique dir name in case you run multiple of this app on the same machine
        default.key.serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000
        auto.offset.reset: latest
logging.level.com.ehsaniara.scs_kafka_intro: debug
