apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: burr-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "burr.apps.ocp.iisi.test"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: burr-vs
spec:
  hosts:
    - '*'
  gateways:
    - burr-gateway
  http:    
    - match:
        - uri:
            prefix: /order
      route:
        - destination:
            host: scs-101-order
            port:
              number: 8080
    
---